import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Filter,Image as ImageIcon,MapPin,RefreshCw,Share2,Tag,UserRound,WalletCards} from 'lucide-react';
import {supabase} from '../lib/supabase';

type Details=Record<string,unknown>;
type Post={id:string;author_id:string;title:string;content?:string|null;images?:unknown;price_iqd?:number|null;city?:string|null;status:string;created_at:string;publisher_name?:string|null;post_type?:string|null;publisher_role?:string|null;label?:string|null;visibility:string;listing_details?:Details|null};
const TYPES=[{value:'all',label:'هەموو'},{value:'food',label:'خواردن'},{value:'fashion',label:'جلوبەرگ'},{value:'marketplace',label:'بازاڕ'},{value:'car',label:'ئۆتۆمبێل'},{value:'umrah',label:'عومرە'},{value:'delivery',label:'گەیاندن'},{value:'announcement',label:'ئاگاداری'}];
const labelFor=(type?:string|null,label?:string|null)=>label||TYPES.find(item=>item.value===type)?.label||'گشتی';
const postImage=(images:unknown)=>Array.isArray(images)&&images.length&&typeof images[0]==='string'?images[0] as string:null;
const isNew=(createdAt:string)=>Date.now()-new Date(createdAt).getTime()<86400000;
const timeLabel=(createdAt:string)=>{const m=Math.floor(Math.max(0,Date.now()-new Date(createdAt).getTime())/60000);if(m<1)return 'ئێستا';if(m<60)return `${m} خولەک لەمەوبەر`;const h=Math.floor(m/60);if(h<24)return `${h} کاتژمێر لەمەوبەر`;return `${Math.floor(h/24)} ڕۆژ لەمەوبەر`;};
function postShareUrl(id:string){const u=new URL(window.location.href);u.search='';u.searchParams.set('post',id);u.hash='shakh-posts';return u.toString();}
async function sharePost(post:Post):Promise<'shared'|'copied'|'cancelled'|'failed'>{try{const url=postShareUrl(post.id);if(typeof navigator.share==='function'){await navigator.share({title:post.title,text:post.content||post.title,url});return 'shared';}if(navigator.clipboard){await navigator.clipboard.writeText(url);return 'copied';}return 'failed';}catch(error){if(error instanceof DOMException&&error.name==='AbortError')return 'cancelled';return 'failed';}}
function specChips(post:Post){const d=post.listing_details||{};if(post.post_type==='fashion')return [d.clothing_type,d.audience,d.size,d.color,d.shoe_size&&`پێلاو ${d.shoe_size}`,d.condition,d.brand&&`براند: ${d.brand}`].filter(Boolean).map(String);if(post.post_type==='car')return [d.make&&`${d.make} ${d.model||''}`,d.year,d.trim&&`Trim: ${d.trim}`,d.mileage&&`${Number(d.mileage).toLocaleString('en-US')} km`,d.engine&&`مەکینە: ${d.engine}`,d.body_type,d.fuel,d.transmission,d.drivetrain,d.color,d.condition].filter(Boolean).map(String);return [];}

export default function PostsFeed(){
 const [posts,setPosts]=useState<Post[]>([]),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(true),[page,setPage]=useState(1),[message,setMessage]=useState(''),[selectedPost,setSelectedPost]=useState<Post|null>(null),[shareMessage,setShareMessage]=useState('');
 const pageSize=12,closeButtonRef=useRef<HTMLButtonElement|null>(null),[,setTimeTick]=useState(0);
 useEffect(()=>{const t=window.setInterval(()=>setTimeTick(v=>v+1),60000);return()=>window.clearInterval(t)},[]);
 const openPost=(post:Post)=>{setSelectedPost(post);setShareMessage('');const u=new URL(window.location.href);u.search='';u.searchParams.set('post',post.id);u.hash='shakh-posts';window.history.replaceState(null,'',u.pathname+u.search+u.hash)};
 const closePost=()=>{setSelectedPost(null);setShareMessage('');const u=new URL(window.location.href);u.searchParams.delete('post');u.hash='shakh-posts';window.history.replaceState(null,'',u.pathname+u.search+u.hash)};
 const load=async()=>{setLoading(true);const {data,error}=await supabase.from('posts').select('id,author_id,title,content,images,price_iqd,city,status,created_at,publisher_name,post_type,publisher_role,label,visibility,listing_details').eq('status','approved').eq('visibility','public').order('created_at',{ascending:false}).limit(200);if(error){setMessage('نەتوانرا پۆستەکان وەرگیرێن.');setLoading(false);return;}setPosts((data||[]) as Post[]);setMessage('');setLoading(false)};
 useEffect(()=>{void load();const c=supabase.channel('shakh-live-posts').on('postgres_changes',{event:'*',schema:'public',table:'posts'},()=>{void load()}).subscribe();return()=>{void supabase.removeChannel(c)}},[]);
 const filtered=useMemo(()=>filter==='all'?posts:posts.filter(p=>p.post_type===filter),[posts,filter]),shown=filtered.slice(0,page*pageSize);useEffect(()=>setPage(1),[filter]);
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('post');if(id&&!selectedPost){const m=posts.find(p=>p.id===id);if(m)setSelectedPost(m)}},[posts,selectedPost]);
 useEffect(()=>{if(!selectedPost)return;const f=posts.find(p=>p.id===selectedPost.id);if(f)setSelectedPost(f);else closePost()},[posts]);
 useEffect(()=>{if(!selectedPost)return;const prev=document.body.style.overflow;document.body.style.overflow='hidden';const key=(e:KeyboardEvent)=>{if(e.key==='Escape')closePost()};window.addEventListener('keydown',key);window.setTimeout(()=>closeButtonRef.current?.focus(),0);return()=>{document.body.style.overflow=prev;window.removeEventListener('keydown',key)}},[selectedPost]);
 return <section className="section postFeed" id="shakh-posts">
  <div className="title postFeedTitle"><div><span>پۆستەکانی شاخ</span><h2>نوێترین ناوەڕۆک لە بازاڕی شاخ</h2></div><button type="button" className="plain" onClick={()=>void load()} disabled={loading} aria-label="نوێکردنەوەی پۆستەکان"><RefreshCw size={17}/></button></div>
  <div className="postFeedFilters" role="tablist" aria-label="فلتەری بەشەکان"><Filter size={17}/>{TYPES.map(item=><button key={item.value} type="button" role="tab" aria-selected={filter===item.value} className={filter===item.value?'active':''} onClick={()=>setFilter(item.value)}>{item.label}</button>)}</div>
  {loading&&!posts.length?<div className="postFeedEmpty"><RefreshCw size={35}/><strong>پۆستەکان بار دەکرێن...</strong><small>کەمێک چاوەڕوان بە.</small></div>:!filtered.length?<div className="postFeedEmpty"><Tag size={38}/><strong>هیچ پۆستێک نەدۆزرایەوە</strong><small>{filter==='all'?'هێشتا پۆستێکی بڵاوکراوە نییە.':'لەو بەشەدا پۆستێک نییە.'}</small></div>:<div className="postFeedGrid">{shown.map(post=>{const img=postImage(post.images),chips=specChips(post);return <article className="postFeedCard" key={post.id} id={'post-'+post.id} tabIndex={0} role="button" aria-label={'پۆستی '+post.title+' بکەرەوە'} onClick={()=>openPost(post)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openPost(post)}}}>
   <div className="postFeedImage">{img?<img src={img} alt={post.title} loading="lazy" decoding="async"/>:<ImageIcon size={40}/>}<span className="postFeedBadge">{labelFor(post.post_type,post.label)}</span>{isNew(post.created_at)&&<span className="postFeedNew">نوێ</span>}</div>
   <div className="postFeedBody"><div className="postFeedMeta"><span><MapPin size={12}/>{post.city||'هەولێر'}</span><small>{timeLabel(post.created_at)}</small></div><h3>{post.title}</h3>{post.content&&<p>{post.content}</p>}{chips.length>0&&<div className="postSpecChips">{chips.map((chip,i)=><span key={`${chip}-${i}`}>{chip}</span>)}</div>}<div className="postFeedPublisher"><UserRound size={14}/><span>{post.publisher_name||'بڵاوکەرەوە'}</span></div><div className="postFeedFooter">{post.price_iqd!=null?<strong><WalletCards size={14}/>{Number(post.price_iqd).toLocaleString('en-US')} د.ع</strong>:<small>بێ نرخ</small>}<span>{post.status==='approved'?'پەسەندکراو':'چاوەڕوان'}</span></div></div>
  </article>})}</div>}
  {shown.length<filtered.length&&<div className="postFeedMore"><button type="button" className="plain" onClick={()=>setPage(v=>v+1)}>زیاتر پیشاندان</button></div>}{message&&<div className="msg postFeedMessage" role="alert" aria-live="polite">{message}</div>}
  {selectedPost&&<div className="postDetailsBackdrop" role="presentation" onClick={closePost}><div className="postDetailsModal" role="dialog" aria-modal="true" aria-labelledby="post-details-title" onClick={e=>e.stopPropagation()}><button ref={closeButtonRef} type="button" className="postDetailsClose" onClick={closePost} aria-label="داخستنی وردەکاریی پۆست"><span>×</span></button><div className="postDetailsImage" role="img" aria-label={selectedPost.title}>{postImage(selectedPost.images)?<img src={postImage(selectedPost.images)||''} alt={selectedPost.title} loading="lazy" decoding="async"/>:<ImageIcon size={46}/>}</div><div className="postDetailsBody"><div className="postDetailsMeta"><span>{labelFor(selectedPost.post_type,selectedPost.label)}</span><small>{selectedPost.city||'هەولێر'}</small></div><h3 id="post-details-title">{selectedPost.title}</h3>{selectedPost.content&&<p>{selectedPost.content}</p>}{specChips(selectedPost).length>0&&<div className="postSpecChips postSpecChipsDetails">{specChips(selectedPost).map((chip,i)=><span key={`${chip}-${i}`}>{chip}</span>)}</div>}<div className="postDetailsPublisher"><UserRound size={15}/><span>{selectedPost.publisher_name||'بڵاوکەرەوە'}</span></div>{selectedPost.price_iqd!=null&&<strong className="postDetailsPrice"><WalletCards size={15}/>{Number(selectedPost.price_iqd).toLocaleString('en-US')} د.ع</strong>}<button type="button" className="primary postDetailsShare" onClick={async()=>{const r=await sharePost(selectedPost);if(r==='shared')setShareMessage('پۆستەکە بە سەرکەوتوویی هاوبەش کرا.');else if(r==='copied')setShareMessage('لینکی پۆستەکە کۆپی کرا.');else if(r==='failed')setShareMessage('نەتوانرا لینکەکە هاوبەش بکرێت.');else setShareMessage('')}}><Share2 size={15}/> هاوبەشکردنی پۆست</button>{shareMessage&&<div className="msg" role="status" aria-live="polite">{shareMessage}</div>}</div></div></div>}
 </section>;
}
