import React,{useEffect,useMemo,useState} from 'react';
import {CheckCircle2,Eye,ImagePlus,Send,Sparkles,Tag,Upload,X} from 'lucide-react';
import {supabase} from '../lib/supabase';

type Props={userId:string;role:string;onSaved?:()=>void};
type RoleConfig={types:{value:string;label:string}[];heading:string;label:string};
const CONFIG:Record<string,RoleConfig>={
 customer:{types:[{value:'general',label:'گشتی'},{value:'marketplace',label:'بازاڕ'}],heading:'پۆستی نوێ',label:'کڕیار'},
 captain:{types:[{value:'delivery',label:'گەیاندن'}],heading:'پۆستی گەیاندن',label:'کاپتن'},
 restaurant_vendor:{types:[{value:'restaurant',label:'خواردن'},{value:'marketplace',label:'بازاڕ'}],heading:'پۆستی ڕێستوران',label:'فرۆشیاری خواردن'},
 fashion_vendor:{types:[{value:'fashion',label:'جلوبەرگ'},{value:'marketplace',label:'بازاڕ'}],heading:'پۆستی جلوبەرگ',label:'فرۆشیاری جلوبەرگ'},
 car_dealer:{types:[{value:'car',label:'ئۆتۆمبێل'}],heading:'SHAKH Cars',label:'پێشانگای ئۆتۆمبێل'},
 umrah_agency:{types:[{value:'umrah',label:'عومرە'}],heading:'پۆستی عومرە',label:'ئاژانسی عومرە'},
 admin:{types:[{value:'announcement',label:'ئاگاداری'},{value:'support',label:'پشتگیری'}],heading:'پۆستی بەڕێوەبەر',label:'بەڕێوەبەر'},
 super_admin:{types:[{value:'announcement',label:'ئاگاداری'},{value:'support',label:'پشتگیری'}],heading:'پۆستی بەڕێوەبەری باڵا',label:'بەڕێوەبەری باڵا'},
 support:{types:[{value:'support',label:'پشتگیری'},{value:'announcement',label:'ئاگاداری'}],heading:'پۆستی پشتگیری',label:'تیمی پشتگیری'}
};
const IRAQ_CITIES=['هەولێر','سلێمانی','دهۆک','کەرکووک','بەغدا','مووسڵ','کەربەلا','نەجەف','بەسرە','ئەنبار','دیالە','واسط','میسان','ذی قار','قادسیە','مثنی','بابل','صلاحەدین'];
const typeIcons:Record<string,string>={general:'💬',marketplace:'🛍️',delivery:'🛵',restaurant:'🍽️',fashion:'👕',car:'🚗',umrah:'🕋',announcement:'📢',support:'🛟'};
const FIELD_OPTIONS={
 audience:['پیاوان','ئافرەتان','منداڵان','هەمووان'],
 clothingType:['تیشێرت','کراس','پانتۆڵ','جین','جاكەت','پۆشاک','جلوبەرگی وەرزشی','پێلاو','جانتا','ئاکسسوارات','کۆمەڵە جلوبەرگ'],
 condition:['نوێ','بەکارهاتوو'],
 colors:['ڕەش','سپی','خۆڵەمەشی','قاوەیی','شین','سۆر','سەوز','زەرد','پەمەیی','کەسک'],
 carCondition:['نوێ','کارکراو'], fuel:['بنزین','دیزڵ','هايبرید','کارەبا'], transmission:['ئۆتۆماتیک','مانوێڵ'], body:['سەدان','SUV','کروس ئۆڤەر','هەچبەک','پیکاپ','ڤان','کوپێ'], drivetrain:['FWD','RWD','AWD','4WD'], plate:['هەیە','نییە'], origin:['ئیمارات','ئەڵمانیا','ئەمریکا','کۆریا','ژاپۆن','چین','تورکیا','عێراق']
};
const CLOTHING_SIZES=['XS','S','M','L','XL','XXL','3XL','28','30','32','34','36','38','40','42','44'];

export default function RolePostComposer({userId,role,onSaved}:Props){
 const cfg=CONFIG[role]||CONFIG.customer;
 const [postType,setPostType]=useState(cfg.types[0].value),[title,setTitle]=useState(''),[content,setContent]=useState(''),[price,setPrice]=useState(''),[city,setCity]=useState('هەولێر');
 const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[showPreview,setShowPreview]=useState(true);
 const [fashion,setFashion]=useState({audience:'',clothingType:'',size:'',color:'',shoeSize:'',condition:'',brand:''});
 const [car,setCar]=useState({make:'',model:'',year:'',trim:'',mileage:'',engine:'',body:'',fuel:'',transmission:'',drivetrain:'',color:'',condition:'',origin:'',plate:'',negotiable:true,exchange:false});
 const isFashion=postType==='fashion',isCar=postType==='car';
 const isPriceVisible=useMemo(()=>postType==='marketplace'||isCar||postType==='umrah',[postType]);
 const ready=Boolean(title.trim()&&(!isPriceVisible||Number(price)>0)&&(!isFashion||fashion.audience&&fashion.clothingType&&fashion.size&&fashion.color&&fashion.condition)&&(!isCar||car.make&&car.model&&car.year&&car.mileage&&car.body&&car.fuel&&car.transmission&&car.color));
 const hasChanges=Boolean(file||title.trim()||content.trim()||price.trim()||city!=='هەولێر'||postType!==cfg.types[0].value||Object.values(fashion).some(Boolean)||Object.values(car).some(v=>v!==''&&v!==true&&v!==false));
 const setF=(key:keyof typeof fashion,value:string)=>setFashion(v=>({...v,[key]:value));
 const setC=(key:keyof typeof car,value:string|boolean)=>setCar(v=>({...v,[key]:value));
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 const chooseFile=(next?:File)=>{if(!next)return;if(!['image/jpeg','image/png','image/webp'].includes(next.type))return setMessage('تەنها فایلێکی وێنە هەڵبژێرە.');if(next.size>5*1024*1024)return setMessage('قەبارەی وێنە نابێت لە ٥ MB زیاتر بێت.');if(preview)URL.revokeObjectURL(preview);setFile(next);setPreview(URL.createObjectURL(next));setMessage('');};
 const clearImage=()=>{if(preview)URL.revokeObjectURL(preview);setFile(null);setPreview('');};
 const submit=async()=>{try{if(!title.trim())return setMessage('سەردێڕ پڕ بکەرەوە.');if(price&&(!/^\d+$/.test(price)||Number(price)<=0))return setMessage('نرخ دەبێت ژمارەی دروست و زیاتر لە سفر بێت.');if(isFashion&&!fashion.audience)return setMessage('تکایە بۆ کێ جلوبەرگەکەیە دیاری بکە.');if(isFashion&&!fashion.clothingType)return setMessage('تکایە جۆری جلوبەرگ دیاری بکە.');if(isFashion&&!fashion.size)return setMessage('تکایە قەبارە دیاری بکە.');if(isFashion&&!fashion.color)return setMessage('تکایە ڕەنگ دیاری بکە.');if(isCar&&!car.make)return setMessage('مارکەی ئۆتۆمبێل دیاری بکە.');if(isCar&&!car.model)return setMessage('مۆدێلی ئۆتۆمبێل دیاری بکە.');setBusy(true);setMessage('');let imageUrl:string|null=null;const {data:profile}=await supabase.from('profiles').select('full_name').eq('id',userId).maybeSingle();const publisherName=(profile as {full_name?:string|null}|null)?.full_name||cfg.label;
  if(file){const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=userId+'/posts/'+Date.now()+'-'+safeName;const {error:uploadError}=await supabase.storage.from('products').upload(path,file,{upsert:false,contentType:file.type});if(uploadError)throw uploadError;imageUrl=supabase.storage.from('products').getPublicUrl(path).data.publicUrl;}
  const listingDetails=isFashion?{category:'fashion',audience:fashion.audience,clothing_type:fashion.clothingType,size:fashion.size,color:fashion.color,shoe_size:fashion.shoeSize||null,condition:fashion.condition,brand:fashion.brand||null}:isCar?{category:'car',make:car.make,model:car.model,year:Number(car.year),trim:car.trim||null,mileage:Number(car.mileage),engine:car.engine||null,body_type:car.body,fuel:car.fuel,transmission:car.transmission,drivetrain:car.drivetrain||null,color:car.color,condition:car.condition,origin:car.origin||null,plate_status:car.plate||null,negotiable:car.negotiable,exchange_allowed:car.exchange}:{};
  const {error}=await supabase.from('posts').insert({author_id:userId,title:title.trim(),content:content.trim()||null,images:imageUrl?[imageUrl]:[],price_iqd:price?Number(price):null,city:city.trim()||'هەولێر',status:'approved',section:postType,publisher_name:publisherName,post_type:postType,publisher_role:role,label:cfg.label,visibility:'public',listing_details:listingDetails});if(error)throw error;
  clearImage();setTitle('');setContent('');setPrice('');setCity('هەولێر');setFashion({audience:'',clothingType:'',size:'',color:'',shoeSize:'',condition:'',brand:''});setCar({make:'',model:'',year:'',trim:'',mileage:'',engine:'',body:'',fuel:'',transmission:'',drivetrain:'',color:'',condition:'',origin:'',plate:'',negotiable:true,exchange:false});setShowPreview(true);setMessage('پۆستەکە بە سەرکەوتوویی بڵاوکرایەوە.');onSaved?.();
 }catch(error:unknown){setMessage(error instanceof Error?error.message:'پۆستکردن سەرکەوتوو نەبوو.');}finally{setBusy(false);}};
 const select=(label:string,value:string,options:string[],onChange:(v:string)=>void)=><label className="postField"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}><option value="">هەڵبژێرە</option>{options.map(o=><option key={o} value={o}>{o}</option>)}</select></label>;
 return <section className="orderCard postComposer" aria-label="پۆستکردن">
  <div className="postComposerHead"><div><span className="eyebrow"><Sparkles size={13}/> پۆستکردنی پیشەیی</span><h3>{cfg.heading}</h3><p>{cfg.label} · لەگەڵ شاخ دەگەیتە لوتکە</p></div><div className="postComposerBadge"><Tag size={21}/><span>{cfg.label}</span></div></div>
  <div className="postComposerLabel">جۆری پۆست</div><div className="postCategoryGrid">{cfg.types.map(item=><button key={item.value} type="button" className={postType===item.value?'postCategory active':'postCategory'} onClick={()=>setPostType(item.value)}><span>{typeIcons[item.value]||'📝'}</span><b>{item.label}</b></button>)}</div>
  {isFashion&&<div className="postStructuredBox"><div className="postComposerLabel">👕 زانیاری جلوبەرگ</div><div className="postFormGrid">{select('بۆ کێیە؟',fashion.audience,FIELD_OPTIONS.audience,v=>setF('audience',v))}{select('جۆری جلوبەرگ',fashion.clothingType,FIELD_OPTIONS.clothingType,v=>setF('clothingType',v))}{select('قەبارە',fashion.size,CLOTHING_SIZES,v=>setF('size',v))}{select('ڕەنگ',fashion.color,FIELD_OPTIONS.colors,v=>setF('color',v))}{select('حاڵەت',fashion.condition,FIELD_OPTIONS.condition,v=>setF('condition',v))}<label className="postField"><span>ژمارەی پێلاو</span><input inputMode="numeric" value={fashion.shoeSize} onChange={e=>setF('shoeSize',e.target.value.replace(/\D/g,''))} placeholder="نموونە: ٤٢"/></label><label className="postField"><span>براند</span><input value={fashion.brand} onChange={e=>setF('brand',e.target.value)} placeholder="نموونە: Nike"/></label></div></div>}
  {isCar&&<div className="postStructuredBox carListingBox"><div className="postComposerLabel">🚗 SHAKH Cars — زانیاریی تەواوی ئۆتۆمبێل</div><div className="postFormGrid"><label className="postField"><span>مارکە</span><input value={car.make} onChange={e=>setC('make',e.target.value)} placeholder="Toyota"/></label><label className="postField"><span>مۆدێل</span><input value={car.model} onChange={e=>setC('model',e.target.value)} placeholder="Land Cruiser"/></label><label className="postField"><span>ساڵ</span><input inputMode="numeric" value={car.year} onChange={e=>setC('year',e.target.value.replace(/\D/g,''))} placeholder="2024"/></label><label className="postField"><span>تریم</span><input value={car.trim} onChange={e=>setC('trim',e.target.value)} placeholder="GXR / Limited"/></label><label className="postField"><span>کیلۆمەتر</span><input inputMode="numeric" value={car.mileage} onChange={e=>setC('mileage',e.target.value.replace(/\D/g,''))} placeholder="45000"/></label><label className="postField"><span>مەکینە</span><input value={car.engine} onChange={e=>setC('engine',e.target.value)} placeholder="3.5L / 6 Cylinder"/></label>{select('جۆری بۆدی',car.body,FIELD_OPTIONS.body,v=>setC('body',v))}{select('سووتەمەنی',car.fuel,FIELD_OPTIONS.fuel,v=>setC('fuel',v))}{select('گێڕ',car.transmission,FIELD_OPTIONS.transmission,v=>setC('transmission',v))}{select('درايفترەین',car.drivetrain,FIELD_OPTIONS.drivetrain,v=>setC('drivetrain',v))}{select('ڕەنگ',car.color,FIELD_OPTIONS.colors,v=>setC('color',v))}{select('حاڵەت',car.condition,FIELD_OPTIONS.carCondition,v=>setC('condition',v))}{select('سەرچاوە',car.origin,FIELD_OPTIONS.origin,v=>setC('origin',v))}{select('پلاک',car.plate,FIELD_OPTIONS.plate,v=>setC('plate',v))}</div><div className="postToggleRow"><label><input type="checkbox" checked={car.negotiable} onChange={e=>setC('negotiable',e.target.checked)}/> نرخ دانوستاندن هەیە</label><label><input type="checkbox" checked={car.exchange} onChange={e=>setC('exchange',e.target.checked)}/> گۆڕین/ئەکسچێنج قبوڵە</label></div></div>}
  <label className="postField"><span className="postLabelRow"><span>سەردێڕ</span><small>{title.length}/100</small></span><input maxLength={100} value={title} onChange={e=>setTitle(e.target.value)} placeholder={isCar?'نموونە: Toyota Land Cruiser 2024':isFashion?'نموونە: جلی ژنانەی نوێ':'سەردێڕی پۆست'}/></label>
  <label className="postField"><span className="postLabelRow"><span>ناوەڕۆک</span><small>{content.length}/500</small></span><textarea rows={5} maxLength={500} value={content} onChange={e=>setContent(e.target.value)} placeholder="پەیام، زانیاری، ڕووداو یان ناوەڕۆکی پۆست..."/></label>
  <div className="postFormGrid">{isPriceVisible&&<label className="postField"><span>نرخ بە د.ع</span><input aria-label="نرخ بە دیناری عێراقی" maxLength={14} value={price} onChange={e=>setPrice(e.target.value.replace(/[^0-9]/g,''))} inputMode="numeric" placeholder="نموونە: ٢٥٠٠٠"/></label>}<label className="postField"><span>شار</span><select value={city} onChange={e=>setCity(e.target.value)}>{IRAQ_CITIES.map(item=><option key={item} value={item}>{item}</option>)}</select></label></div>
  <div className="postUploadBox"><div className="postUploadHead"><div><b>{isCar?'وێنەکانی ئۆتۆمبێل':isFashion?'وێنەکانی جلوبەرگ':'وێنەی پۆست'}</b><small>JPG، PNG یان WEBP · تا ٥ MB</small></div><ImagePlus size={20}/></div><label className={preview?'postUploadDrop hasImage':'postUploadDrop'} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();chooseFile(e.dataTransfer.files?.[0])}}><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>chooseFile(e.target.files?.[0])}/>{preview?<><img src={preview} alt={title||'پێشبینینی پۆست'}/><span className="postUploadOverlay">گۆڕینی وێنە</span></>:<><Upload size={24}/><b>وێنە هەڵبژێرە</b><small>کلیک بکە و وێنەی پۆست هەڵبژێرە</small></>}</label>{preview&&<button type="button" className="postRemoveImage" onClick={clearImage}><X size={15}/> سڕینەوەی وێنە</button>}</div>
  <div className="postComposerBottom"><span className="postComposerHint">پۆستەکە لە داتابەیسی شاخ هەڵدەگیرێت و لە Feed ـدا بە شێوەی ڕاستەقینە دەردەکەوێت.</span><button type="button" className="postPreviewToggle" onClick={()=>setShowPreview(v=>!v)}><Eye size={16}/>{showPreview?'شاردنەوەی پێشبینین':'پیشاندانی پێشبینین'}</button></div>
  {showPreview&&<div className="postLivePreview"><div className="postLivePreviewTop"><span>پێشبینینی پۆست</span><small>{typeIcons[postType]||'📝'} {cfg.types.find(item=>item.value===postType)?.label||cfg.label}</small></div><div className="postLivePreviewCard"><div className="postLivePreviewImage">{preview?<img src={preview} alt=""/>:<ImagePlus size={34}/>}</div><div className="postLivePreviewBody"><small>{cfg.label} · {city}</small><h4>{title.trim()||'سەردێڕی پۆستەکەت لێرە دەردەکەوێت'}</h4><p>{content.trim()||'ناوەڕۆکی پۆستەکەت لێرە پیشان دەدرێت.'}</p>{isPriceVisible&&<div className="postLivePreviewPrice">{price?Number(price).toLocaleString('en-US'):'٠'} د.ع</div>}</div></div></div>}
  <button type="button" className="postResetButton" disabled={busy||!hasChanges} onClick={()=>{if(!window.confirm('دڵنیایت؟ هەموو گۆڕانکارییەکانی فۆڕمەکە لەدەست دەچێت.'))return;clearImage();setTitle('');setContent('');setPrice('');setCity('هەولێر');setPostType(cfg.types[0].value);setFashion({audience:'',clothingType:'',size:'',color:'',shoeSize:'',condition:'',brand:''});setCar({make:'',model:'',year:'',trim:'',mileage:'',engine:'',body:'',fuel:'',transmission:'',drivetrain:'',color:'',condition:'',origin:'',plate:'',negotiable:true,exchange:false});setMessage('فۆڕمەکە پاک کرایەوە.')}}>پاککردنەوەی فۆڕم</button>
  <button type="button" className="primary postPublishButton" disabled={busy||!ready} onClick={()=>void submit()}>{busy?<><Upload size={17}/> بڵاوکردنەوە...</>:<><Send size={17}/> بڵاوکردنەوەی پۆست</>}</button>
  {message&&<div className={message.includes('سەرکەوت')?'postComposerMessage success':'postComposerMessage'} role="alert" aria-live="polite">{message}</div>}
  <small className="postComposerFoot"><CheckCircle2 size={14}/> پۆستەکان لە داتابەیسی شاخ هەڵدەگیرێن و Realtime ـیش چالاکە.</small>
 </section>;
}
