import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient,User} from '@supabase/supabase-js';
import {Search,ShoppingBag,User as UserIcon,Bell,Store,Truck,Wallet,ArrowLeft,LogOut,Minus,Plus,Trash2,X,MapPin,PackageCheck,LayoutDashboard,RefreshCw,Car,Plane} from 'lucide-react';
import './styles.css';
import CustomerOrdersPanel from './components/CustomerOrdersPanel';
import CaptainDashboard from './components/CaptainDashboard';
import VendorDashboard from './components/VendorDashboard';
import SuperAdminOrderMonitor from './components/SuperAdminOrderMonitor';
import VehicleShowroomModule from './components/VehicleShowroomModule';
import UmrahBookingModule from './components/UmrahBookingModule';

const url=import.meta.env.VITE_SUPABASE_URL as string|undefined;
const key=import.meta.env.VITE_SUPABASE_ANON_KEY as string|undefined;
const supabase=url&&key?createClient(url,key):null;

type Product={id:string;store_id:string;name_ku:string;name_ar?:string;name_en?:string;price_iqd:number;sale_price_iqd?:number|null;image_url?:string|null;is_available:boolean;category?:string;store_name?:string};
type CartItem={id?:string;product_id:string;store_id:string;name:string;price:number;quantity:number;image_url?:string|null};
type Order={id:string;status:string;total_iqd:number;created_at:string;store_id?:string};
type DashboardView='home'|'orders'|'delivery'|'store'|'wallet'|'cars'|'umrah';

function PasswordReset(){
 const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [message,setMessage]=useState('');
 const update=async()=>{if(!supabase)return setMessage('پەیوەندی بە خزمەتگوزاری بەردەست نییە.');if(password.length<6)return setMessage('وشەی نهێنی دەبێت لانیکەم ٦ پیت بێت.');if(password!==confirm)return setMessage('دوو وشەی نهێنی یەکسان نین.');const {error}=await supabase.auth.updateUser({password});setMessage(error?.message||'وشەی نهێنی بە سەرکەوتوویی گۆڕدرا.');};
 return <div className="app"><main><div className="auth" style={{margin:'80px auto'}}><div className="mark">شاخ</div><h2>گۆڕینی وشەی نهێنی</h2><p>وشەی نهێنی نوێی خۆت بنووسە.</p><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="وشەی نهێنی نوێ"/><input value={confirm} onChange={e=>setConfirm(e.target.value)} type="password" placeholder="دووبارە وشەی نهێنی"/><button className="primary full" onClick={update}>گۆڕینی وشەی نهێنی</button>{message&&<small className="msg">{message}</small>}</div></main></div>;
}

function App(){
 const [products,setProducts]=useState<Product[]>([]);const [search,setSearch]=useState('');const [cart,setCart]=useState<CartItem[]>([]);const [cartOpen,setCartOpen]=useState(false);const [checkoutOpen,setCheckoutOpen]=useState(false);const [dashboard,setDashboard]=useState(false);const [dashboardView,setDashboardView]=useState<DashboardView>('home');const [address,setAddress]=useState('');const [auth,setAuth]=useState(false);const [authMode,setAuthMode]=useState<'login'|'signup'|'reset'>('login');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [message,setMessage]=useState('');const [user,setUser]=useState<User|null>(null);const [role,setRole]=useState('customer');const [orders,setOrders]=useState<Order[]>([]);const [busy,setBusy]=useState(false);
 const loadProducts=async()=>{if(!supabase)return;const {data,error}=await supabase.from('products').select('id,store_id,name_ku,name_ar,name_en,price_iqd,sale_price_iqd,image_url,is_available,stores(name),categories(name)').eq('is_available',true).order('created_at',{ascending:false});if(!error&&data)setProducts((data as any[]).map(p=>({...p,store_name:p.stores?.name,category:p.categories?.name})))};
 const loadCart=async(u:User)=>{if(!supabase)return;const {data:c}=await supabase.from('carts').select('id').eq('user_id',u.id).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(!c){setCart([]);return}const {data:items}=await supabase.from('cart_items').select('id,product_id,quantity,unit_price_iqd,products(store_id,name_ku,image_url)').eq('cart_id',c.id);setCart((items as any[]||[]).map(i=>({id:i.id,product_id:i.product_id,store_id:i.products?.store_id,name:i.products?.name_ku||'بەرهەم',price:Number(i.unit_price_iqd),quantity:i.quantity,image_url:i.products?.image_url})))};
 const loadProfile=async(u:User)=>{if(!supabase)return;const {data}=await supabase.from('profiles').select('role').eq('id',u.id).maybeSingle();setRole(data?.role||'customer')};
 const loadOrders=async(u:User)=>{if(!supabase)return;const {data}=await supabase.from('orders').select('id,status,total_iqd,created_at,store_id').eq('customer_id',u.id).order('created_at',{ascending:false}).limit(20);if(data)setOrders(data as Order[])};
 useEffect(()=>{if(!supabase)return;let mounted=true;supabase.auth.getSession().then(({data})=>{if(mounted&&data.session?.user){setUser(data.session.user);loadProfile(data.session.user);loadCart(data.session.user);loadOrders(data.session.user)}});const {data:listener}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user??null);if(session?.user){loadProfile(session.user);loadCart(session.user);loadOrders(session.user)}else{setCart([]);setOrders([]);setRole('customer')}});loadProducts();const channel=supabase.channel('shakh-live-products').on('postgres_changes',{event:'*',schema:'public',table:'products'},()=>loadProducts()).subscribe();return()=>{mounted=false;listener.subscription.unsubscribe();supabase.removeChannel(channel)}},[]);
 const filtered=useMemo(()=>products.filter(p=>(p.name_ku||'').toLowerCase().includes(search.toLowerCase())),[products,search]);
 const subtotal=cart.reduce((s,i)=>s+i.price*i.quantity,0);const delivery=cart.length?1000:0;const platformFee=cart.length?250:0;const total=subtotal+delivery+platformFee;
 const ensureCart=async(u:User,storeId:string)=>{if(!supabase)throw new Error('پەیوەندی بە خزمەتگوزاری بەردەست نییە.');const {data,error}=await supabase.from('carts').select('id').eq('user_id',u.id).eq('store_id',storeId).maybeSingle();if(error)throw error;if(data)return data.id as string;const {data:created,error:ce}=await supabase.from('carts').insert({user_id:u.id,store_id:storeId}).select('id').single();if(ce)throw ce;return created.id as string};
 const addToCart=async(p:Product)=>{if(!user){setAuthMode('login');setAuth(true);setMessage('بۆ زیادکردن بۆ سەلە، تکایە بچۆ ژوورەوە یان خۆت تۆمار بکە.');return}try{setBusy(true);if(cart.length&&cart[0].store_id!==p.store_id){setMessage('لە هەر سەلەیەکدا تەنها لە یەک دوکان دەتوانیت داواکاری بکەیت.');return}const cartId=await ensureCart(user,p.store_id);const price=Number(p.sale_price_iqd??p.price_iqd);const existing=cart.find(i=>i.product_id===p.id);if(existing?.id)await supabase!.from('cart_items').update({quantity:existing.quantity+1}).eq('id',existing.id);else{const {error}=await supabase!.from('cart_items').insert({cart_id:cartId,product_id:p.id,quantity:1,unit_price_iqd:price});if(error)throw error}await loadCart(user);setMessage('بەرهەمەکە بۆ سەلە زیاد کرا.')}catch(e:any){setMessage(e?.message||'زیادکردنی بەرهەم سەرکەوتوو نەبوو.')}finally{setBusy(false)}};
 const changeQty=async(item:CartItem,delta:number)=>{if(!item.id||!supabase)return;const q=item.quantity+delta;if(q<=0)await supabase.from('cart_items').delete().eq('id',item.id);else await supabase.from('cart_items').update({quantity:q}).eq('id',item.id);if(user)await loadCart(user)};
 const clearCart=async()=>{if(!supabase||!user)return;const ids=cart.map(i=>i.id).filter(Boolean) as string[];if(ids.length)await supabase.from('cart_items').delete().in('id',ids);setCart([])};
 const checkout=async()=>{if(!user){setCartOpen(false);setAuthMode('login');setAuth(true);setMessage('بۆ تەواوکردنی داواکارییەکەت، تکایە بچۆ ژوورەوە یان خۆت تۆمار بکە.');return}if(!cart.length)return setMessage('سەلەکەت بەتاڵە.');if(!address.trim())return setMessage('تکایە ناونیشانی گەیاندن بنووسە.');try{setBusy(true);const storeId=cart[0].store_id;const {data:addr,error:ae}=await supabase!.from('delivery_addresses').insert({user_id:user.id,label:'ناونیشانی ئۆردەر',address:address.trim(),city:'هەولێر',is_default:false}).select('id').single();if(ae)throw ae;const {data:order,error:oe}=await supabase!.from('orders').insert({customer_id:user.id,store_id:storeId,status:'pending',address_id:addr.id,subtotal_iqd:subtotal,delivery_fee_iqd:delivery,platform_fee_iqd:platformFee,discount_iqd:0,total_iqd:total,payment_status:'pending',payment_method:'cash'}).select('id').single();if(oe)throw oe;const rows=cart.map(i=>({order_id:order.id,product_id:i.product_id,product_name:i.name,quantity:i.quantity,unit_price_iqd:i.price,options:{}}));const {error:ie}=await supabase!.from('order_items').insert(rows);if(ie)throw ie;await clearCart();await loadOrders(user);setCheckoutOpen(false);setCartOpen(false);setAddress('');setMessage(`داواکارییەکەت بە سەرکەوتوویی تۆمار کرا. ژمارەی داواکاری: ${order.id.slice(0,8)}`)}catch(e:any){setMessage(e?.message||'تۆمارکردنی داواکاری سەرکەوتوو نەبوو.')}finally{setBusy(false)}};
 const login=async()=>{if(!supabase)return setMessage('پەیوەندی بە خزمەتگوزاری بەردەست نییە.');const {error}=await supabase.auth.signInWithPassword({email,password});setMessage(error?.message||'بە سەرکەوتوویی چوویتە ژوورەوە.');};
 const signup=async()=>{if(!supabase)return setMessage('پەیوەندی بە خزمەتگوزاری بەردەست نییە.');if(password.length<6)return setMessage('وشەی نهێنی دەبێت لانیکەم ٦ پیت بێت.');const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});setMessage(error?.message||(data.session?'هەژمارەکەت دروست کرا.':'هەژمارەکەت دروست کرا؛ تکایە ئیمەیڵەکەت پشتڕاست بکەرەوە.'));};
 const google=async()=>{if(!supabase)return setMessage('پەیوەندی بە خزمەتگوزاری بەردەست نییە.');const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}});if(error)setMessage(error.message)};
 const reset=async()=>{if(!supabase||!email)return setMessage('تکایە ئیمەیڵەکەت بنووسە.');const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/reset-password'});setMessage(error?.message||'لینکی گۆڕینی وشەی نهێنی بۆ ئیمەیڵەکەت نێردرا.')};
 const signout=async()=>{await supabase?.auth.signOut();setAuth(false);setDashboard(false);setDashboardView('home')};
 const openDashboard=(view:DashboardView='home')=>{setDashboardView(view);setDashboard(true);if(user)void loadOrders(user)};
 const roleLabel=role==='super_admin'?'بەڕێوبەری باڵا':role==='admin'?'بەڕێوبەر':role==='restaurant_vendor'||role==='fashion_vendor'?'خاوەن دوکان':role==='captain'?'کاپتن':role==='car_dealer'?'پێشانگای ئۆتۆمبێل':role==='umrah_agency'?'کۆمپانیای حەج و عومرە':'کڕیار';
 const dashboardModule=()=>{
  if(!user)return null;
  if(dashboardView==='orders'){
   if(role==='super_admin'||role==='admin')return <SuperAdminOrderMonitor/>;
   return <CustomerOrdersPanel userId={user.id}/>;
  }
  if(dashboardView==='delivery'){
   if(role==='captain')return <CaptainDashboard/>;
   if(role==='super_admin'||role==='admin')return <SuperAdminOrderMonitor/>;
   return <CustomerOrdersPanel userId={user.id}/>;
  }
  if(dashboardView==='store'){
   if(role==='restaurant_vendor'||role==='fashion_vendor')return <VendorDashboard onRefresh={()=>void loadProducts()} productCount={products.length} pendingOrders={orders.filter(o=>o.status==='pending').length} todaySales={orders.reduce((s,o)=>s+Number(o.total_iqd||0),0)}/>;
   if(role==='car_dealer')return <VehicleShowroomModule userId={user.id}/>;
   if(role==='umrah_agency')return <UmrahBookingModule userId={user.id} role={role}/>;
   if(role==='super_admin'||role==='admin')return <SuperAdminOrderMonitor/>;
   return <CustomerOrdersPanel userId={user.id}/>;
  }
  if(dashboardView==='cars')return <VehicleShowroomModule userId={user.id} isAdmin={role==='super_admin'||role==='admin'}/>;
  if(dashboardView==='umrah')return <UmrahBookingModule userId={user.id} role={role}/>;
  return null;
 };
 return <div className="app" dir="rtl"><header><div className="nav"><div className="logo"><b>شاخ</b><span>بازاڕی هەموو شت</span></div><div className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="گەڕان لە خواردن، بازاڕ و بەرهەم..."/></div><button className="plain" onClick={()=>user?openDashboard('orders'):(setAuthMode('login'),setAuth(true))} aria-label="ئاگادارکردنەوە"><Bell/></button><button className="cart" onClick={()=>setCartOpen(true)}><ShoppingBag/><i>{cart.reduce((s,i)=>s+i.quantity,0)}</i></button>{user&&<button className="plain" title="داشبۆرد" onClick={()=>openDashboard('home')}><LayoutDashboard/></button>}{user?<button className="loginBtn" onClick={signout}><LogOut size={17}/> دەرچوون</button>:<button className="loginBtn" onClick={()=>{setAuthMode('login');setAuth(true)}}><UserIcon size={17}/> چوونەژوورەوە</button>}</div></header>
 <main><section className="hero"><div><span className="eyebrow">بازاڕی زیندووی شاخ</span><h1>هەموو شتێک،<strong> لە یەک شوێن.</strong></h1><p>خواردن، سوپرمارکێت، جل و بەرگ، ئۆتۆمبێل و گەشتەکانی حەج و عومرە لە یەک پلاتفۆرم.</p><button className="primary" onClick={()=>document.querySelector('.section')?.scrollIntoView({behavior:'smooth'})}>دەستپێبکە <ArrowLeft/></button></div><div className="heroOrb">🛍️</div></section>
 <section className="section"><div className="title"><span>بازاڕی شاخ</span><h2>بەرهەمە بەردەستەکان</h2></div>{!filtered.length?<div className="empty"><PackageCheck size={40}/><h3>هێشتا بەرهەمێک بەردەست نییە</h3><p>کاتێک خاوەن دوکان بەرهەم زیاد بکات، لێرە بە شێوەی زیندوو دەردەکەوێت.</p></div>:<div className="grid">{filtered.map(p=>{const price=Number(p.sale_price_iqd??p.price_iqd);return <article className="card" key={p.id}><div className="pic">{p.image_url?<img src={p.image_url} alt={p.name_ku}/>:<span>🛍️</span>}</div><div className="body"><small>{p.category||'بازاڕ'} · {p.store_name||'دوکان'}</small><h3>{p.name_ku}</h3><div className="buy"><b>{price.toLocaleString('en-US')} د.ع</b><button disabled={busy||!p.is_available} onClick={()=>addToCart(p)}>+ زیادکردن</button></div></div></article>})}</div>}</section>
 <section className="features"><button type="button" onClick={()=>openDashboard('delivery')}><Truck/><b>گەیاندنی خێرا</b><small>بەدواداچوونی داواکاری</small></button><button type="button" onClick={()=>openDashboard('store')}><Store/><b>دوکان و پێشانگا</b><small>بازاڕ و فرۆشتنی ڕاستەوخۆ</small></button><button type="button" onClick={()=>openDashboard('cars')}><Car/><b>SHAKH Cars</b><small>پێشانگا، پۆستکردن و پەسەندکردن</small></button><button type="button" onClick={()=>openDashboard('umrah')}><Plane/><b>حەج و عومرە</b><small>تەنها حجزکردنی گەشت</small></button><button type="button" onClick={()=>openDashboard('wallet')}><Wallet/><b>جزدان</b><small>پارە و خاڵەکان</small></button></section></main>
 {message&&<div className="toast"><span>{message}</span><button onClick={()=>setMessage('')}><X size={16}/></button></div>}
 {cartOpen&&<div className="modal"><div className="auth cartPanel"><button className="x" onClick={()=>setCartOpen(false)}>×</button><h2>سەلەی من</h2>{!cart.length?<div className="empty"><ShoppingBag size={42}/><h3>سەلەکەت بەتاڵە</h3><p>بەرهەمەکان زیاد بکە بۆ دەستپێکردنی داواکاری.</p></div>:<><div className="cartList">{cart.map(i=><div className="cartRow" key={i.id}><div><b>{i.name}</b><small>{i.price.toLocaleString('en-US')} د.ع</small></div><div className="qty"><button onClick={()=>changeQty(i,-1)}><Minus size={15}/></button><b>{i.quantity}</b><button onClick={()=>changeQty(i,1)}><Plus size={15}/></button><button className="danger" onClick={()=>changeQty(i,-i.quantity)}><Trash2 size={15}/></button></div></div>)}</div><div className="summary"><div><span>کۆی بەرهەم</span><b>{subtotal.toLocaleString('en-US')} د.ع</b></div><div><span>گەیاندن</span><b>{delivery.toLocaleString('en-US')} د.ع</b></div><div><span>خزمەتی شاخ</span><b>{platformFee.toLocaleString('en-US')} د.ع</b></div><div className="grand"><span>کۆی گشتی</span><b>{total.toLocaleString('en-US')} د.ع</b></div></div><button className="primary full" onClick={()=>{if(!user){setCartOpen(false);setAuthMode('login');setAuth(true);setMessage('بۆ تەواوکردنی داواکارییەکەت، تکایە چوونەژوورەوە بکە.')}else setCheckoutOpen(true)}}>تەواوکردنی داواکاری</button></>}</div></div>}
 {checkoutOpen&&<div className="modal"><div className="auth"><button className="x" onClick={()=>setCheckoutOpen(false)}>×</button><div className="mark"><MapPin/></div><h2>ناونیشانی گەیاندن</h2><p>ناونیشانی وردی شوێنی گەیاندنت بنووسە.</p><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="نموونە: هەولێر، گەڕەکی ..."/><button className="primary full" disabled={busy} onClick={checkout}>{busy?'تکایە چاوەڕێ بکە':'تۆمارکردنی داواکاری'}</button></div></div>}
 {dashboard&&user&&<div className="modal"><div className="auth dashboardPanel"><button className="x" onClick={()=>{setDashboard(false);setDashboardView('home')}}>×</button>{dashboardView!=='home'&&<><button className="reset" type="button" onClick={()=>setDashboardView('home')}>← گەڕانەوە بۆ سەرەکی داشبۆرد</button><div style={{marginTop:16}}>{dashboardModule()}</div></>}{dashboardView==='home'&&<><div className="dashHead"><div><small>داشبۆردی شاخ</small><h2>{roleLabel}</h2><p>{user.email}</p></div><button className="plain" onClick={()=>loadOrders(user)}><RefreshCw size={18}/></button></div><div className="dashCards"><button type="button" onClick={()=>openDashboard('orders')}><b>{orders.length}</b><span>داواکارییەکان</span></button><button type="button" onClick={()=>openDashboard('delivery')}><b>{orders.filter(o=>o.status==='pending').length}</b><span>چاوەڕوان</span></button><button type="button" onClick={()=>openDashboard('orders')}><b>{orders.reduce((s,o)=>s+Number(o.total_iqd||0),0).toLocaleString('en-US')}</b><span>کۆی پارەی داواکاری</span></button></div><div className="roleTiles"><button type="button" onClick={()=>openDashboard('store')}><Store/><b>دوکانەکان</b><small>{roleLabel==='خاوەن دوکان'?'بەشی بەڕێوەبردنی دوکان':'بینینی بازاڕ و ئۆردەر'}</small></button><button type="button" onClick={()=>openDashboard('delivery')}><Truck/><b>گەیاندن</b><small>شوێنکەوتنی داواکاری و دۆخی گەیاندن</small></button><button type="button" onClick={()=>openDashboard('cars')}><Car/><b>SHAKH Cars</b><small>پێشانگاکان و پۆستەکانی ئۆتۆمبێل</small></button><button type="button" onClick={()=>openDashboard('umrah')}><Plane/><b>حەج و عومرە</b><small>حجز، پارەی حجز و پارەی سەفەر</small></button><button type="button" onClick={()=>openDashboard('wallet')}><Wallet/><b>جزدان</b><small>بەشی جزدان و خاڵەکان</small></button></div><h3 className="dashTitle">نوێترین داواکارییەکان</h3>{!orders.length?<p className="msg">هێشتا هیچ داواکارییەکت نییە.</p>:<div className="orderList">{orders.map(o=><button type="button" className="orderRow" key={o.id} onClick={()=>openDashboard('orders')}><div><b>داواکاری #{o.id.slice(0,8)}</b><small>{new Date(o.created_at).toLocaleString('ku-IQ')}</small></div><span>{o.status==='pending'?'چاوەڕوان':o.status}</span><strong>{Number(o.total_iqd).toLocaleString('en-US')} د.ع</strong></button>)}</div>}</>}</div></div>}
 {auth&&<div className="modal"><div className="auth"><button className="x" onClick={()=>setAuth(false)}>×</button><div className="mark">شاخ</div>{authMode==='reset'?<><h2>گەڕاندنەوەی وشەی نهێنی</h2><p>لینکی گۆڕینی وشەی نهێنی بۆ ئیمەیڵەکەت دەنێرین.</p><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="ئیمەیڵ"/><button className="primary full" onClick={reset}>ناردنی لینک</button><button className="reset" onClick={()=>setAuthMode('login')}>گەڕانەوە بۆ چوونەژوورەوە</button></>:<><h2>{authMode==='login'?'بەخێربێیت بۆ شاخ':'هەژماری نوێ دروست بکە'}</h2>{authMode==='signup'&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="ناوی تەواو"/>}<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="ئیمەیڵ"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="وشەی نهێنی"/><button className="primary full" onClick={authMode==='login'?login:signup}>{authMode==='login'?'چوونەژوورەوە':'تۆمارکردن'}</button><div className="or">یان</div><button className="google" onClick={google}>چوونەژوورەوە بە گووگڵ</button>{authMode==='login'&&<button className="reset" onClick={()=>setAuthMode('reset')}>وشەی نهێنیت لەبیرچووە؟</button>}<button className="reset" onClick={()=>setAuthMode(authMode==='login'?'signup':'login')}>{authMode==='login'?'هەژمارت نییە؟ تۆماربە':'هەژمارت هەیە؟ بچۆ ژوورەوە'}</button>{message&&<small className="msg">{message}</small>}</>}</div></div>}
 </div>;
}

const path=window.location.pathname;
createRoot(document.getElementById('root')!).render(path==='/reset-password'?<PasswordReset/>:<App/>);